---
title: "black_scholes_checkpoint"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Replicating code

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(PerformanceAnalytics)
library(dplyr)
library(tidyverse)

df <- read.csv("daily-closing-prices.csv")
df$date <- as.character(df$date)
df$date <- sub("(.{4})(.{2})(.{2})", "\\1-\\2-\\3", df$date)
df$date <- as.Date(df$date)

estimate_sigma <- function (x){
  diff1 <- diff(x)
  denominator <- x[1:nrow(as.data.frame(x))-1]
  sd(diff1 / denominator)
}

rownames(df) <- df[,1]
df[,1] <- NULL

df$sigma_20 <- apply.rolling(df, width=20, FUN="estimate_sigma")

to_cbind <- df$sigma_20
rownames(to_cbind) <- NULL
df <- cbind(df, to_cbind)
colnames(df) <- c("closing_price", "sigma_to_erase", "sigma_20")
df[,2] <- NULL

df$date <- rownames(df)

date_sigma <- df[, c("date", "closing_price", "sigma_20")]
date_sigma
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(knitr)
library(dplyr)
library(tidyverse)
library(forcats)
library(gridExtra)
library(RSQLite)
library(jsonlite)
library(gtable)
library(grid)
library(latex2exp)
library(gridBase)
library(nnet)
library(magrittr)
library(ggplot2)
library(sos)
library(scales)

dcon <- dbConnect(SQLite(), dbname = "option_price.db")
query1 <- paste0("
SELECT *
FROM option_price;
")

res <- dbSendQuery(conn = dcon, query1)
df2 <- dbFetch(res, -1)
dbClearResult(res)

head(df2)
```

## PreProcess

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df2$date_ndiff <- as.Date(as.character(df2$exdate), format="%Y/%m/%d") - as.Date(as.character(df2$date), format="%Y/%m/%d")
head(df2$date_ndiff)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
options_df <- df2
options_df$treasury_rate <- 1.76

options_df2 <- options_df[, c("date", "strike_price", "best_bid", "best_offer", "volume", "open_interest", "date_ndiff", "treasury_rate", "cp_flag")]

options_df2$date <- as.Date(options_df2$date)
date_sigma$date <- as.Date(date_sigma$date)
str(options_df2$date)
str(date_sigma$date)

options_df_with_sigma <- merge(x=options_df2, y=date_sigma, by="date", all.x=TRUE)

nrow(options_df_with_sigma)

options_df_new <- na.omit(options_df_with_sigma)

nrow(options_df_new)

options_df_new_put <- options_df_new %>% filter(cp_flag == "P")
nrow(options_df_new_put)

options_df_new_call <- options_df_new %>% filter(cp_flag == "C")
nrow(options_df_new_call)

black_scholes_put <- function(row){
  S <- as.numeric(row["closing_price"])
  X <- as.numeric(row["strike_price"]) / 1000
  T_ <- as.numeric(row["date_ndiff"]) / 365
  r <- as.numeric(row["treasury_rate"]) / 100
  sigma <- as.numeric(row["sigma_20"])
  d1 <- (log(S / X) + (r  + (sigma ** 2) / 2) * T_) / (sigma * (T_ ** 0.5))
  d2 <- d1 - sigma * (T_ ** 0.5)
  P <- pnorm(-d2) * X * exp(-r * T_) - S * pnorm(-d1)
  P
}

black_scholes <- function(row){
  S <- as.numeric(row["closing_price"])
  X <- as.numeric(row["strike_price"]) / 1000
  T_ <- as.numeric(row["date_ndiff"]) / 365
  r <- as.numeric(row["treasury_rate"]) / 100
  sigma <- as.numeric(row["sigma_20"])
  d1 <- (log(S / X) + (r + (sigma ** 2) / 2) * T_) / (sigma * (T_ ** 0.5))
  d2 <-  d1 - sigma * (T_ ** 0.5)
  C <- S * pnorm(d1) - X * exp(-r * T_) * pnorm(d2)
  C
}

# call
options_df_new_call$date_ndiff <- as.numeric(options_df_new_call$date_ndiff)

black_scholes_pred <- apply(options_df_new_call, MARGIN = 1, black_scholes)
black_scholes_pred <- as.data.frame(black_scholes_pred)
options_df_new_call <- cbind(options_df_new_call, black_scholes_pred)

mse <- function(df){
  temp <- as.matrix(rowMeans(df[, c("best_bid", "best_offer")])) - as.matrix(df[, c("black_scholes_pred")])
  squared <- temp ** 2
  sum <- sum(squared)
  mse <- sum / nrow(df)
  mse
}

call_mse <- mse(options_df_new_call)

med_abs_err <- function(df){
  temp <- as.matrix(rowMeans(df[, c("best_bid", "best_offer")])) - as.matrix(df[, c("black_scholes_pred")])
  abs_val <- abs(temp)
  print(abs_val)
  index1 <- nrow(df) %/% 2
  print(index1)
  return_val <- abs_val[index1]
  return_val
}

call_med_abs_err <- med_abs_err(options_df_new_call)

# checkpoint
dim(options_df_new_call)
write.csv(options_df_new_call, "C:/Users/robin/Desktop/RStudio/options_new_call.csv")

# put
options_df_new_put$date_ndiff <- as.numeric(options_df_new_put$date_ndiff)

black_scholes_pred2 <- apply(options_df_new_put, MARGIN = 1, black_scholes_put)
black_scholes_pred2 <- as.data.frame(black_scholes_pred2)
options_df_new_put <- cbind(options_df_new_put, black_scholes_pred2)

bid_ask_avg <- as.matrix(rowMeans(options_df_new_put[, c("best_bid", "best_offer")]))

# rmse = sqrt(mean(square(bid_ask_avg - pred2)))
# med-err = median(bid_ask_avg - pred2)
# avg-abs-err = mean(abs(bid_ask_spread - pred2))
# med-abs-dev = median(abs(bid_ask_spread - pred2))

```
