---
title: "black_scholes_final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Black Scholes

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(PerformanceAnalytics)
library(dplyr)
library(tidyverse)
```

# Separating Call Options and Put Options

```{r, echo=TRUE, message=FALSE, warning=FALSE}
options_bs <- read.csv("msft_final_df2.csv")
head(options_bs)
options_both <- options_bs[, c("date", "exdate", "cp_flag", "strike_price", "best_bid", "best_offer", "volume", "open_interest", "impl_volatility", "date_ndiff", "treasury_rate", "closing_price", "sigma_20")]

# dropping columns impl_volatility and exdate
options_both[, 9] <- NULL
options_both[, 2] <- NULL

# dropping NA values from treasury_rate column
options_both$treasury_rate <- as.numeric(options_both$treasury_rate)
summary(options_both$treasury_rate)
nrow(options_both)
options_both <- na.omit(options_both)
nrow(options_both)

options_put <- options_both %>% filter(cp_flag == "P")
options_put[, 2] <- NULL
nrow(options_put)
head(options_put)

options_call <- options_both %>% filter(cp_flag == "C")
options_call[, 2] <- NULL
nrow(options_call)
head(options_call)
```

# Black Scholes Model: Call and Put Functions

```{r, echo=TRUE, message=FALSE, warning=FALSE}
black_scholes_put <- function(row){
  S <- as.numeric(row["closing_price"])
  X <- as.numeric(row["strike_price"]) / 1000
  T_ <- as.numeric(row["date_ndiff"]) / 365
  r <- as.numeric(row["treasury_rate"]) / 100
  sigma <- as.numeric(row["sigma_20"])
  d1 <- (log(S / X) + (r  + (sigma ** 2) / 2) * T_) / (sigma * (T_ ** 0.5))
  d2 <- d1 - sigma * (T_ ** 0.5)
  P <- pnorm(-d2) * X * exp(-r * T_) - S * pnorm(-d1)
  P
}

black_scholes <- function(row){
  S <- as.numeric(row["closing_price"])
  X <- as.numeric(row["strike_price"]) / 1000
  T_ <- as.numeric(row["date_ndiff"]) / 365
  r <- as.numeric(row["treasury_rate"]) / 100
  sigma <- as.numeric(row["sigma_20"])
  d1 <- (log(S / X) + (r + (sigma ** 2) / 2) * T_) / (sigma * (T_ ** 0.5))
  d2 <-  d1 - sigma * (T_ ** 0.5)
  C <- S * pnorm(d1) - X * exp(-r * T_) * pnorm(d2)
  C
}
```

# Call Options

```{r, echo=TRUE, message=FALSE, warning=FALSE}
# mean squared error function
mse <- function(df){
  temp <- as.matrix(rowMeans(df[, c("best_bid", "best_offer")])) - as.matrix(df[, c("black_scholes_pred")])
  squared <- temp ** 2
  sum <- sum(squared)
  mse <- sum / nrow(df)
  mse
}

# median absolute error function
med_abs_err <- function(df){
  temp <- as.matrix(rowMeans(df[, c("best_bid", "best_offer")])) - as.matrix(df[, c("black_scholes_pred")])
  abs_val <- abs(temp)
  index1 <- nrow(df) %/% 2
  return_val <- abs_val[index1]
  return_val
}

# getting BS prediction values for call options
options_call$black_scholes_pred <- apply(options_call, MARGIN = 1, black_scholes)
head(options_call)

call_mse <- mse(options_call)
call_mse

call_med_abs_err <- med_abs_err(options_call)
call_med_abs_err
```

# Put Options

```{r, echo=TRUE, message=FALSE, warning=FALSE}
# getting BS prediction values for put options
options_put$black_scholes_pred <- apply(options_put, MARGIN = 1, black_scholes_put)
head(options_put)

put_mse <- mse(options_put)
put_mse

put_med_abs_err <- med_abs_err(options_put)
put_med_abs_err

# other metrics tested on put options
bid_ask_avg <- as.matrix(rowMeans(options_put[, c("best_bid", "best_offer")]))
bid_ask_avg_minus_pred <- bid_ask_avg - as.matrix(options_put$black_scholes_pred)

rmse <- sqrt(mean(bid_ask_avg_minus_pred ** 2))
rmse
med_err <- median(bid_ask_avg_minus_pred)
med_err
avg_abs_err <- mean(abs(bid_ask_avg_minus_pred))
avg_abs_err
med_abs_dev <- median(abs(bid_ask_avg_minus_pred))
med_abs_dev
```